[general]
import = [
  "./catppuccin-mocha.toml"
]

[window]
opacity = 0.8
blur = true

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
